In [12]:
import numpy as np
import re
import scipy.spatial

In [3]:
file_obj = open('sentences.txt')
data_list = list(file_obj)
print(data_list[:3])

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n']


In [4]:
data_list = list(map(lambda x: x.lower() , data_list))

In [5]:
print(data_list[:3])

['in comparison to dogs, cats have not undergone major changes during the domestication process.\n', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n', 'a common interactive use of cat for a single file is to output the content of a file to standard output.\n']


In [6]:
words = list(map(lambda x: re.split('[^a-z]', x), data_list))
print(len(words))
print(words[:3])

22
[['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', ''], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', ''], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', '']]


In [7]:
all_words = list()
for w in words:
    for l in w:
        all_words.append(l)
print(len(all_words))
print(all_words)

635
['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', '', 'as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', '', 'a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', '', 'cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', '', '', 'in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', '', '', 'the', 'domesticated', 'cat', 'and', 'its', 'closest'

In [8]:
#for w in all_words:
#    all_words.remove('')
#print(len(all_words))
#print(all_words)

In [9]:
words_dict = dict()
for w in all_words:
    if w != '':
        words_dict[w] = 0
i = -1
for w in words_dict:
    # words_dict[w] = words_dict[w] + 1
    i += 1
    words_dict[w] = i
print(len(words_dict))        
print(words_dict)

254
{'x': 0, 'instead': 1, 'redirected': 2, 'single': 3, 'pipes': 4, 'other': 5, 'mac': 6, 'some': 7, 'which': 8, 'unix': 9, 'genus': 10, 'such': 11, 'any': 12, 'have': 13, 'now': 14, 'later': 15, 'apple': 16, 'selection': 17, 'july': 18, 'recent': 19, 'can': 20, 'useful': 21, 'features': 22, 'cat': 23, 'one': 24, 'when': 25, 'domesticated': 26, 'where': 27, 'between': 28, 'enhancements': 29, 'wild': 30, 'during': 31, 'allows': 32, 'predecessor': 33, 'update': 34, 'sounds': 35, 'both': 36, 'as': 37, 'longer': 38, 'changes': 39, 'moved': 40, 'purchase': 41, 'in': 42, 'sequence': 43, 'was': 44, 'run': 45, 'create': 46, 'flow': 47, 'simply': 48, 'installs': 49, 'processors': 50, 'also': 51, 'year': 52, 'upgrade': 53, 'may': 54, 'displays': 55, 'high': 56, 'weighing': 57, 'mavericks': 58, 'they': 59, 'stdout': 60, 'lines': 61, 'mid': 62, 'bytes': 63, 'or': 64, 'process': 65, 'hear': 66, 'learned': 67, 'is': 68, 'interactive': 69, 'patch': 70, 'stdin': 71, 'allow': 72, 'major': 73, 'non': 7

In [10]:
words_dist = np.zeros((len(words), len(words_dict)))

for i in range(len(words)):
    for j in range(len(words[i])):
        if words[i][j] != '':
            words_dist[i, words_dict[words[i][j]]] = words_dist[i, words_dict[words[i][j]]] + 1
            
print(words_dist[:15,:15])

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [29]:
dist = np.zeros(22)
for i in range(len(words)):
    dist[i] = scipy.spatial.distance.cosine(words_dist[0], words_dist[i])
    
print(dist)

[ 0.          0.95275444  0.86447381  0.89517152  0.77708871  0.94023857
  0.73273876  0.92587507  0.88427249  0.90550888  0.83281654  0.88047714
  0.83964325  0.87035926  0.87401184  0.94427218  0.84063619  0.9566445
  0.94427218  0.88854436  0.84275727  0.82503645]


In [34]:
np.sort(dist)

array([ 0.        ,  0.73273876,  0.77708871,  0.82503645,  0.83281654,
        0.83964325,  0.84063619,  0.84275727,  0.86447381,  0.87035926,
        0.87401184,  0.88047714,  0.88427249,  0.88854436,  0.89517152,
        0.90550888,  0.92587507,  0.94023857,  0.94427218,  0.94427218,
        0.95275444,  0.9566445 ])